from typing import Literal

from pydantic import BaseModel, Field, HttpUrl


class EventRequest(BaseModel):
    """Client event payload for the currently supported tracking events."""

    event_type: Literal[
        "create_course_clicked",
        "date_course_explore_clicked",
        "save_course_clicked",
    ]
    session_id: str = Field(
        ...,
        min_length=1,
        max_length=128,
        description="Anonymous session identifier generated by the client.",
    )
    page_url: HttpUrl = Field(
        ...,
        description="Full URL of the page where the event occurred.",
    )
    attempt_id: str | None = Field(
        default=None,
        max_length=128,
        description=(
            "Required for create_course_clicked and save_course_clicked "
            "(탐색 시도 단위 짝 맞추기)."
        ),
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "event_type": "create_course_clicked",
                    "session_id": "sess_01HZXYZ",
                    "page_url": "https://example.com/planner",
                    "attempt_id": "att_01HZXYZ",
                },
                {
                    "event_type": "save_course_clicked",
                    "session_id": "sess_01HZXYZ",
                    "page_url": "https://example.com/planner",
                    "attempt_id": "att_01HZXYZ",
                },
                {
                    "event_type": "date_course_explore_clicked",
                    "session_id": "sess_01HZXYZ",
                    "page_url": "https://example.com/explore",
                },
            ]
        }
    }
